title:            xiaoo_gan
description:      iOS、Java、美剧、古典音乐.
logo:             xiaoo_gan.jpg
duoshuo_short_name: ever223
# Assign a default image for your site's header and footer
default_bg:       default_bg1.jpg
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Turn on or off the fin animations in the header and footer
animated_fins:    true
triangleheader:   true
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
# url:              "http://localhost:4000"


# Owner/author information
owner:
  name:           xiaoo_gan
  avatar:         xiaoo_gan.jpg
  email:          85265900@qq.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:     Coder
  # Social networking links used in footer. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  # twitter:
  # facebook:
  github: ever223
  # linkedin:
  # instagram:
  tumblr: blog/xiaoogan
  weibo: xiaogan223
  # hmfaysalsocial:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:    "http://plus.google.com/123123123123132123"

# Analytics and webmaster tools stuff goes here
# google_analytics:
# google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: <i class="icon-home"></i> 主页
    url: /
    external: false
    icon: home
  # - title: <i class="icon-book"></i> Documentation
  #   url: /documentation
  - title: <i class="icon-bookmark"></i> 分类
    url: /categories
  - title: <i class="icon-tags"></i> 标签
    url: /tags
#  - title: xiaoo_gan who?
#    url: /hossain-mohd-faysal

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    China/Zhejiang
future:      true
pygments: true
markdown:    kramdown
paginate:    6
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class